2023-05-04 20:51:58,259 INFO    StreamThr :9184 [internal.py:wandb_internal():86] W&B internal server running at pid: 9184, started at: 2023-05-04 20:51:58.258701
2023-05-04 20:51:58,261 DEBUG   HandlerThread:9184 [handler.py:handle_request():144] handle_request: status
2023-05-04 20:51:58,279 INFO    WriterThread:9184 [datastore.py:open_for_write():85] open: f:\Glaucoma\wandb\run-20230504_205158-0x002\run-0x002.wandb
2023-05-04 20:51:58,280 DEBUG   SenderThread:9184 [sender.py:send():375] send: header
2023-05-04 20:51:58,588 DEBUG   SenderThread:9184 [sender.py:send():375] send: run
2023-05-04 20:51:59,296 ERROR   SenderThread:9184 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-04 20:51:59,296 ERROR   SenderThread:9184 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x002 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-04 20:52:00,730 ERROR   SenderThread:9184 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-04 20:52:00,730 ERROR   SenderThread:9184 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x002 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-04 20:52:03,450 ERROR   SenderThread:9184 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-04 20:52:03,450 ERROR   SenderThread:9184 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x002 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-04 20:52:03,451 INFO    SenderThread:9184 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\internal\internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\lib\gql_request.py", line 56, in execute
    request.raise_for_status()
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-05-04 20:52:03,643 DEBUG   HandlerThread:9184 [handler.py:handle_request():144] handle_request: keepalive
2023-05-04 20:52:08,438 ERROR   SenderThread:9184 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-04 20:52:08,439 ERROR   SenderThread:9184 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x002 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-04 20:52:08,710 DEBUG   HandlerThread:9184 [handler.py:handle_request():144] handle_request: keepalive
2023-05-04 20:52:13,766 DEBUG   HandlerThread:9184 [handler.py:handle_request():144] handle_request: keepalive
2023-05-04 20:52:17,598 ERROR   SenderThread:9184 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-04 20:52:17,598 ERROR   SenderThread:9184 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x002 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
