2023-05-03 15:58:46,818 INFO    StreamThr :24196 [internal.py:wandb_internal():86] W&B internal server running at pid: 24196, started at: 2023-05-03 15:58:46.817248
2023-05-03 15:58:46,821 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status
2023-05-03 15:58:46,835 INFO    WriterThread:24196 [datastore.py:open_for_write():85] open: f:\Glaucoma\wandb\run-20230503_155846-0x001\run-0x001.wandb
2023-05-03 15:58:46,836 DEBUG   SenderThread:24196 [sender.py:send():375] send: header
2023-05-03 15:58:46,838 DEBUG   SenderThread:24196 [sender.py:send():375] send: run
2023-05-03 15:58:47,579 ERROR   SenderThread:24196 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-03 15:58:47,579 ERROR   SenderThread:24196 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x001 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-03 15:58:49,051 ERROR   SenderThread:24196 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-03 15:58:49,051 ERROR   SenderThread:24196 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x001 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-03 15:58:49,908 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:58:51,548 ERROR   SenderThread:24196 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-03 15:58:51,548 ERROR   SenderThread:24196 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x001 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-03 15:58:51,548 INFO    SenderThread:24196 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\internal\internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\lib\gql_request.py", line 56, in execute
    request.raise_for_status()
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-05-03 15:58:51,900 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:58:54,955 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:58:56,285 ERROR   SenderThread:24196 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-03 15:58:56,285 ERROR   SenderThread:24196 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x001 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-03 15:58:56,938 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:58:59,996 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:01,975 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:05,021 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:05,834 ERROR   SenderThread:24196 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-03 15:59:05,834 ERROR   SenderThread:24196 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x001 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-03 15:59:07,009 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:10,067 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:12,053 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:15,109 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:17,104 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:20,159 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:22,139 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:22,216 ERROR   SenderThread:24196 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-03 15:59:22,216 ERROR   SenderThread:24196 [internal_api.py:execute():289] {"errors":[{"message":"run webcoders/Glaucoma Detection/0x001 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-03 15:59:25,206 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:27,190 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:30,247 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:32,232 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:35,282 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:37,286 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:40,337 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:42,335 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: keepalive
2023-05-03 15:59:45,366 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:47,367 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: cancel
2023-05-03 15:59:47,367 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: cancel
2023-05-03 15:59:47,368 DEBUG   SenderThread:24196 [sender.py:send():384] Record cancelled: run
2023-05-03 15:59:47,368 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:50,399 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
2023-05-03 15:59:52,391 DEBUG   HandlerThread:24196 [handler.py:handle_request():144] handle_request: status_report
