2023-05-03 15:58:34,291 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-05-03 15:58:34,291 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Configure stats pid to 6184
2023-05-03 15:58:34,291 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Anton\.config\wandb\settings
2023-05-03 15:58:34,292 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Loading settings from f:\Glaucoma\wandb\settings
2023-05-03 15:58:34,292 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-03 15:58:34,292 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-03 15:58:34,292 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-03 15:58:34,292 INFO    MainThread:6184 [wandb_init.py:_log_setup():507] Logging user logs to f:\Glaucoma\wandb\run-20230503_155834-0x001\logs\debug.log
2023-05-03 15:58:34,292 INFO    MainThread:6184 [wandb_init.py:_log_setup():508] Logging internal logs to f:\Glaucoma\wandb\run-20230503_155834-0x001\logs\debug-internal.log
2023-05-03 15:58:34,292 INFO    MainThread:6184 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000023DEB326D60>
2023-05-03 15:58:34,293 INFO    MainThread:6184 [wandb_init.py:init():547] calling init triggers
2023-05-03 15:58:34,293 INFO    MainThread:6184 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'Dataset': 'Glaucoma', 'Models': 'Xception', 'learning_rate': 0.001, 'beta1': 0.9, 'metrics': ['accuracy']}
2023-05-03 15:58:34,293 INFO    MainThread:6184 [wandb_init.py:init():596] starting backend
2023-05-03 15:58:34,293 INFO    MainThread:6184 [wandb_init.py:init():600] setting up manager
2023-05-03 15:58:34,297 INFO    MainThread:6184 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-03 15:58:34,304 INFO    MainThread:6184 [wandb_init.py:init():606] backend started and connected
2023-05-03 15:58:34,320 INFO    MainThread:6184 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-03 15:58:34,323 INFO    MainThread:6184 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-03 15:58:34,323 INFO    MainThread:6184 [wandb_init.py:init():700] updated telemetry
2023-05-03 15:58:34,342 INFO    MainThread:6184 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-03 15:58:34,755 ERROR   MainThread:6184 [wandb_init.py:init():763] encountered error: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (0x001) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2023-05-03 15:58:35,048 ERROR   MainThread:6184 [wandb_init.py:init():1168] You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (0x001) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
Traceback (most recent call last):
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.UsageError: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (0x001) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2023-05-03 15:58:46,809 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-05-03 15:58:46,810 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Configure stats pid to 6184
2023-05-03 15:58:46,810 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Anton\.config\wandb\settings
2023-05-03 15:58:46,810 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Loading settings from f:\Glaucoma\wandb\settings
2023-05-03 15:58:46,810 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-03 15:58:46,810 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-03 15:58:46,811 INFO    MainThread:6184 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-03 15:58:46,811 INFO    MainThread:6184 [wandb_init.py:_log_setup():507] Logging user logs to f:\Glaucoma\wandb\run-20230503_155846-0x001\logs\debug.log
2023-05-03 15:58:46,812 INFO    MainThread:6184 [wandb_init.py:_log_setup():508] Logging internal logs to f:\Glaucoma\wandb\run-20230503_155846-0x001\logs\debug-internal.log
2023-05-03 15:58:46,812 INFO    MainThread:6184 [wandb_init.py:init():547] calling init triggers
2023-05-03 15:58:46,812 INFO    MainThread:6184 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'Dataset': 'Glaucoma', 'Models': 'Xception', 'learning_rate': 0.001, 'beta1': 0.9, 'metrics': ['accuracy']}
2023-05-03 15:58:46,812 INFO    MainThread:6184 [wandb_init.py:init():596] starting backend
2023-05-03 15:58:46,812 INFO    MainThread:6184 [wandb_init.py:init():600] setting up manager
2023-05-03 15:58:46,815 INFO    MainThread:6184 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-03 15:58:46,818 INFO    MainThread:6184 [wandb_init.py:init():606] backend started and connected
2023-05-03 15:58:46,833 INFO    MainThread:6184 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-03 15:58:46,834 INFO    MainThread:6184 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-03 15:58:46,834 INFO    MainThread:6184 [wandb_init.py:init():700] updated telemetry
2023-05-03 15:58:46,837 INFO    MainThread:6184 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-03 15:59:47,367 ERROR   MainThread:6184 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-03 15:59:47,541 ERROR   MainThread:6184 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
